/*
  # Add Invitation Token System

  ## Overview
  Adds a system for admin to generate invitation tokens that users can use to create accounts.

  ## 1. New Tables

  ### invitation_tokens
  - Stores unique invitation tokens generated by admins
  - Each token is linked to a role
  - Tracks creation time and expiration
  - Records when the token was used and by whom

  ## 2. Changes to Users Table
  - Add created_by (admin who created the user account via invitation)
  - Add invitation_token_id (tracks which token was used)

  ## 3. Security
  - Enable RLS on invitation_tokens table
  - Only authenticated admins can create tokens
  - Users can only view their own data
  - Admins can see all users and tokens
*/

CREATE TABLE IF NOT EXISTS invitation_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text UNIQUE NOT NULL,
  role_id uuid NOT NULL REFERENCES roles(id),
  created_by uuid NOT NULL REFERENCES users(id),
  is_used boolean DEFAULT false,
  used_by uuid REFERENCES users(id),
  used_at timestamptz,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

-- Add new columns to users table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'users' AND column_name = 'created_by'
  ) THEN
    ALTER TABLE users ADD COLUMN created_by uuid REFERENCES users(id);
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'users' AND column_name = 'invitation_token_id'
  ) THEN
    ALTER TABLE users ADD COLUMN invitation_token_id uuid REFERENCES invitation_tokens(id);
  END IF;
END $$;

-- Enable RLS on invitation_tokens
ALTER TABLE invitation_tokens ENABLE ROW LEVEL SECURITY;

-- Policies for invitation_tokens
CREATE POLICY "Admins can view all invitation tokens"
  ON invitation_tokens FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users u
      JOIN roles r ON u.role_id = r.id
      WHERE u.id = auth.uid() AND r.name = 'admin'
    )
  );

CREATE POLICY "Admins can create invitation tokens"
  ON invitation_tokens FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users u
      JOIN roles r ON u.role_id = r.id
      WHERE u.id = auth.uid() AND r.name = 'admin'
    ) AND
    created_by = auth.uid()
  );

CREATE POLICY "Admins can update invitation tokens"
  ON invitation_tokens FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users u
      JOIN roles r ON u.role_id = r.id
      WHERE u.id = auth.uid() AND r.name = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users u
      JOIN roles r ON u.role_id = r.id
      WHERE u.id = auth.uid() AND r.name = 'admin'
    )
  );

-- Update users table RLS policies to include invitation_token_id
CREATE POLICY "Admins can insert users"
  ON users FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users u
      JOIN roles r ON u.role_id = r.id
      WHERE u.id = auth.uid() AND r.name = 'admin'
    )
  );

CREATE POLICY "Admins can delete users"
  ON users FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users u
      JOIN roles r ON u.role_id = r.id
      WHERE u.id = auth.uid() AND r.name = 'admin'
    )
  );
